### ISSUE TITLE
Memory of blobholder leaks.

### ISSUE THREAD

**Issue by harryherold** [score-p/scorep_plugin_fileparser#10]
The allocated memory of ```blobholder``` leaks.
Memory is allocated in measurement_blob.c on line 140, see
```
struct blob_holder* blobarray_create(uint64_t initial_capacity, uint64_t initial_value)
{
    /* try a calloc */
    struct blob_holder* container = calloc(1, sizeof(struct blob_holder));
   ...
}
```
but there is no free.

**Comment by Quimoniz** [comment]
thank you for reporting. I fixed this issue with the latest commit 3c018498c9d9880d32c4b09341f8d4509bf179dd
